require('dotenv').config();
const express=require('express'),cors=require('cors'),helmet=require('helmet'),morgan=require('morgan');
const app=express();
app.use(helmet({crossOriginResourcePolicy:false}));
app.use(cors({origin:process.env.FRONTEND_URL||'http://localhost:5173',credentials:true}));
app.use(express.json({limit:'1mb'})); app.use(morgan('dev'));
app.get('/api/health',(req,res)=>res.json({ok:true,service:'DocShare API'}));
app.use('/api/auth',require('./routes/authRoutes'));
app.use('/api/categories',require('./routes/categoryRoutes'));
app.use('/api/documents',require('./routes/documentRoutes'));
app.use('/api/users',require('./routes/userRoutes'));
app.use('/api/admin',require('./routes/adminRoutes'));
app.use((req,res)=>res.status(404).json({message:'API không tồn tại.'}));
app.use((err,req,res,next)=>{console.error(err); if(err.code==='LIMIT_FILE_SIZE')return res.status(400).json({message:'File tối đa 20MB.'}); res.status(400).json({message:err.message||'Yêu cầu không hợp lệ.'});});
const PORT=Number(process.env.PORT||5000); app.listen(PORT,()=>console.log(`DocShare API: http://localhost:${PORT}`));
